stages:
  - build
  - build-image

build-war:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn -B package
  artifacts:
    paths:
      - target/lmdb.war

build-image:
  image: docker:stable
  services:
  - docker:dind
  stage: build-image
  script:
    - docker login -p $CI_JOB_TOKEN registry.gitlab.com -u gitlab-ci-token
    - docker build -t registry.gitlab.com/jensknutson/serverprog .
    - docker push registry.gitlab.com/jensknutson/serverprog
